services:
  db:
    container_name: pokemon_db
    image: postgres:15
    networks:
      - pokemon_net
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pokemon_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pokemon_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  web:
    container_name: pokemon_api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pokemon_net
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/pokemon_db

networks:
  pokemon_net:
    name: pokemon_network
    driver: bridge
